In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# create a vector
vector  = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimensions of vector
vector.ndim

1

In [ ]:
# create a matrix 
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

# Create a matrix (has more than one dimension)
matrix = tf.constant([[10, 7],
                      [7,10]])
matrix

In [ ]:
# create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# lets create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4,5,6]],
                       [[7,8,9],
                       [10, 11, 12]],
                       [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# create a same tensor w tf.Variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
unchangeable_tensor[0].assign(11)

AttributeError: ignored

In [ ]:
# Creating random tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape = (3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape = (3, 2))
random_1, random_2, random_2 == random_1

In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
tf.random.set_seed(24)
tf.random.shuffle(not_shuffled, seed = 24)

In [ ]:
 tf.random.set_seed(42) 
 tf.random.shuffle(not_shuffled, seed = 42)

In [ ]:
tf.ones([10, 7])

In [ ]:
tf.zeros(shape = (3, 4))

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A

In [ ]:
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B
 

In [ ]:
tf.size(A)

In [ ]:
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimesnions : " , rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("elements along the 0 axis: ", rank_4_tensor.shape[0])
print("elements along the last axis ", rank_4_tensor.shape[-1])
print("Totla no of elements in tensor: ", tf.size(rank_4_tensor).numpy())

NameError: ignored

In [ ]:
some_list = [1,2,3,4]
some_list[:2]

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
rank_4_tensor[:1, :1, :1, :]

In [ ]:
rank_2_tensor = tf.constant([[11, 7],
                             [7, 10]])
rank_2_tensor.ndim, rank_2_tensor.shape

In [ ]:
rank_2_tensor[:, -1]

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
tf.expand_dims(rank_2_tensor, axis = -1)

In [ ]:
tf.expand_dims(rank_2_tensor, axis = 0)

In [ ]:
tensor = tf.constant([[10, 7],[3, 4]])
tensor + 10

In [ ]:
tensor - 10

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[-9, -8, -7],
        [-6, -5, -4]],

       [[-3, -2, -1],
        [ 0,  1,  2]],

       [[ 3,  4,  5],
        [ 6,  7,  8]]], dtype=int32)>

In [ ]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]],

       [[130, 140, 150],
        [160, 170, 180]]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


InvalidArgumentError: ignored

In [ ]:
tensor* tensor

In [ ]:
tensor @ tensor

In [ ]:
tensor.shape

In [ ]:
X = tf.constant([[3, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X @ Y

In [ ]:
tf.reshape(Y, shape=(2,3))

In [ ]:
X.shape

NameError: ignored

In [ ]:
X @ tf.reshape(Y, shape=(2, 3))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
tf.transpose(X), tf.reshape(X, shape = (2, 3))


In [ ]:
tf.matmul(tf.transpose(X), Y)

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

NameError: ignored

In [ ]:
tf.tensordot(X, tf.transpose(Y), axes = 1)

In [ ]:
B = tf.constant([[1.7, 7.4]])
B.dtype

In [ ]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

NameError: ignored

In [ ]:
E = tf.cast(C, dtype = tf.float32)
E, E.dtype, C.dtype

In [ ]:
D = tf.constant([-7, -10])
D

In [ ]:
tf.abs(D)

In [ ]:
tf.math.reduce_mean(D)

NameError: ignored

In [ ]:
X = tf.constant([[7, 10],
                 [3, 4]])
Y = tf.constant([[5, 6],
                 [1, 11]])
print(tf.minimum(X, Y))
print(tf.maximum(X, Y))

In [ ]:
tf.add(X, Y)

In [ ]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

In [ ]:
tf.size(E), E.shape, E.ndim

NameError: ignored

In [ ]:
tf.reduce_sum(E)

In [ ]:
tf.reduce_min(E)

In [ ]:
tf.reduce_max(E)

NameError: ignored

In [ ]:
x = tf.reduce_mean(E)

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(E)

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

NameError: ignored

In [ ]:
tf.argmax(E)

In [ ]:
tf.argmin(E)

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
 G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

In [ ]:
depth = 4
list = [0, 1, 2, 3]
tf.one_hot(list, depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(list, depth, on_value="Nishant", off_value = "Parth")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Nishant', b'Parth', b'Parth', b'Parth'],
       [b'Parth', b'Nishant', b'Parth', b'Parth'],
       [b'Parth', b'Parth', b'Nishant', b'Parth'],
       [b'Parth', b'Parth', b'Parth', b'Nishant']], dtype=object)>

In [ ]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H, dtype = tf.bfloat16))

<tf.Tensor: shape=(9,), dtype=bfloat16, numpy=
array([1, 1.41406, 1.73438, 2, 2.23438, 2.45312, 2.64062, 2.82812, 3],
      dtype=bfloat16)>

In [ ]:
tf.math.log(tf.cast(H, dtype = tf.bfloat16))

<tf.Tensor: shape=(9,), dtype=bfloat16, numpy=
array([0, 0.691406, 1.10156, 1.38281, 1.60938, 1.78906, 1.94531, 2.07812,
       2.20312], dtype=bfloat16)>

In [ ]:
import numpy as np
J  = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Sep 19 10:56:04 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------